### ISSUE TITLE
Exception on playlist processing

### ISSUE THREAD

**Issue by gEndelf** [creotiv/deezer_playlist_mp3_downloader#1]
Exception raised on app execution

```
dzget -f mp3 -q 7 --playlist http://www.deezer.com/playlist/1290316405

## Parsing: Napkey - At Least
 > Url: /watch?v=AB3UWDkxPW4
[youtube] AB3UWDkxPW4: Downloading webpage
[youtube] AB3UWDkxPW4: Downloading video info webpage
[youtube] AB3UWDkxPW4: Extracting video information
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/Users/bb/.virtualenvs/deezer/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1081, in _decrypt_signature
    video_id, player_url, s
  File "/Users/bb/.virtualenvs/deezer/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://www.youtube.com/yts/jsbin/player-vfl3DiVMI/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Cannot identify player u'https://www.youtube.com/yts/jsbin/player-vfl3DiVMI/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/bb/.virtualenvs/deezer/bin/dzget", line 11, in <module>
    load_entry_point('Deezer-MP3-Downloader==0.0.4', 'console_scripts', 'dzget')()
  File "/Users/bb/.virtualenvs/deezer/lib/python2.7/site-packages/deezermp3/dzget.py", line 112, in main
    dmp3.download_playlist(args.url)
  File "/Users/bb/.virtualenvs/deezer/lib/python2.7/site-packages/deezermp3/dzget.py", line 61, in download_playlist
    ydl.download(["http://www.youtube.com%s" % videos[0]])
  File "/Users/bb/.virtualenvs/deezer/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1890, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/Users/bb/.virtualenvs/deezer/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 784, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "/Users/bb/.virtualenvs/deezer/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 589, in report_error
    self.trouble(error_message, tb)
  File "/Users/bb/.virtualenvs/deezer/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 559, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/Users/bb/.virtualenvs/deezer/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1081, in _decrypt_signature
    video_id, player_url, s
  File "/Users/bb/.virtualenvs/deezer/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://www.youtube.com/yts/jsbin/player-vfl3DiVMI/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Cannot identify player u'https://www.youtube.com/yts/jsbin/player-vfl3DiVMI/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by creotiv** [comment]
Thanks for report, will investigate asap.

**Comment by creotiv** [comment]
Fixed.
