### ISSUE TITLE
Youtube-dl version issue

### ISSUE THREAD

**Issue by flenoir** [creotiv/deezer_playlist_mp3_downloader#10]
Hi, i get this error

```
Traceback (most recent call last):
  File "C:\Python37\Scripts\dzget-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 3126, in <module>
    @_call_aside
  File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 3110, in _call_aside
    f(*args, **kwargs)
  File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 3139, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 898, in require
    needed = self.resolve(parse_requirements(requirements))
  File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 784, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'youtube-dl==2018.09.18' distribution was not found and is required by Deezer-MP3-Downloader

```
Where can i update the version ?

**Comment by kn00tcn** [comment]
what do you mean, it's a world famous package https://github.com/ytdl-org/youtube-dl/

**Comment by creotiv** [comment]
use another most similar version with that in requirements.txt. They seem to delete some version tag in repository

**Comment by ArtemkaJS** [comment]
The same problem. 
If youtube-dl version = 2018.09.18 then I get the next error:

` ExtractorError: 1yGH0-AwaSI: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

If I update youtube-dl to latest version (2019.9.1) then I get the next error:

```
Traceback (most recent call last):
  File "/home/anisotropy/.local/bin/dzget", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 576, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'youtube-dl==2018.09.18' distribution was not found and is required by Deezer-MP3-Downloader
```

**Comment by creotiv** [comment]
Updated, try now

**Comment by ArtemkaJS** [comment]
> 
> 
> Updated, try now

Thank you! It works!
