### ISSUE TITLE
Unexpected title error when I try to download playlist

### ISSUE THREAD

**Issue by dshuvar** [creotiv/deezer_playlist_mp3_downloader#11]
That a new installation of dzget.

```dzget playlist/6215554404 
Traceback (most recent call last):
  File "/usr/local/bin/dzget", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/deezermp3/dzget.py", line 128, in main
    dmp3.download_playlist(url)
  File "/usr/local/lib/python2.7/site-packages/deezermp3/dzget.py", line 52, in download_playlist
    pl_name = data['title']
KeyError: 'title'

**Comment by camypaj** [comment]
same here - on Linux Mint 19.2.
Tried installing everything with python3, same err:
`python3 /home/theuser/.local/lib/python3.6/site-packages/deezermp3/dzget.py -f mp3  https://www.deezer.com/us/playlist/1234567890
Traceback (most recent call last):
  File "/home/theuser/.local/lib/python3.6/site-packages/deezermp3/dzget.py", line 156, in <module>
    main()
  File "/home/theuser/.local/lib/python3.6/site-packages/deezermp3/dzget.py", line 152, in main
    dmp3.download_playlist(url)
  File "/home/theuser/.local/lib/python3.6/site-packages/deezermp3/dzget.py", line 70, in download_playlist
    pl_name = data['title']
KeyError: 'title'
`
The problem becomes different if I launch the app directly (chmod u+x /usr/local/lib/python2.7/site-packages/deezermp3/dzget.py, and then launching it directly), but then I get some other problems, both with python2.7 and python3.6.
Please try it out (if you still can), and let me know if it changes anything for you.

**Comment by hronoses** [comment]
For me, this error occurred for a private playlist. Make sure the playlist is public. And update youtube-dl
Worked with python 2.7
