### ISSUE TITLE
Fails with ERROR: Signature extraction failed

### ISSUE THREAD

**Issue by artkpv** [creotiv/deezer_playlist_mp3_downloader#2]
Thank you for the tool!

```
> dzget -f mp3 --playlist http://www.deezer.com/playlist/2055454184

## Parsing: Jax Jones - House Work
 > Url: /watch?v=ULC2C3VjO-o
[youtube] ULC2C3VjO-o: Downloading webpage
[youtube] ULC2C3VjO-o: Downloading video info webpage
[youtube] ULC2C3VjO-o: Extracting video information
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "c:\python36\lib\site-packages\youtube_dl\extractor\youtube.py", line 1081, in _decrypt_signature
    video_id, player_url, s
  File "c:\python36\lib\site-packages\youtube_dl\extractor\youtube.py", line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vfltmLGsd/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vfltmLGsd/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\youtube_dl\extractor\youtube.py", line 1081, in _decrypt_signature
    video_id, player_url, s
  File "c:\python36\lib\site-packages\youtube_dl\extractor\youtube.py", line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vfltmLGsd/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 761, in extract_info
    ie_result = ie.extract(url)
  File "c:\python36\lib\site-packages\youtube_dl\extractor\common.py", line 429, in extract
    ie_result = self._real_extract(url)
  File "c:\python36\lib\site-packages\youtube_dl\extractor\youtube.py", line 1670, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "c:\python36\lib\site-packages\youtube_dl\extractor\youtube.py", line 1091, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "c:\python36\lib\site-packages\youtube_dl\extractor\youtube.py", line 1081, in _decrypt_signature
    video_id, player_url, s
  File "c:\python36\lib\site-packages\youtube_dl\extractor\youtube.py", line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vfltmLGsd/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vfltmLGsd/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python36\Scripts\dzget-script.py", line 11, in <module>
    load_entry_point('Deezer-MP3-Downloader==0.0.4', 'console_scripts', 'dzget')()
  File "c:\python36\lib\site-packages\deezermp3\dzget.py", line 112, in main
    dmp3.download_playlist(args.url)
  File "c:\python36\lib\site-packages\deezermp3\dzget.py", line 61, in download_playlist
    ydl.download(["http://www.youtube.com%s" % videos[0]])
  File "c:\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 1890, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "c:\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 784, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "c:\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 589, in report_error
    self.trouble(error_message, tb)
  File "c:\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 559, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
  File "c:\python36\lib\site-packages\youtube_dl\extractor\youtube.py", line 1081, in _decrypt_signature
    video_id, player_url, s
  File "c:\python36\lib\site-packages\youtube_dl\extractor\youtube.py", line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vfltmLGsd/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vfltmLGsd/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
It is 

```
> youtube-dl.exe --version
2017.04.03
```

**Comment by artkpv** [comment]
After upgrading 'youtube-dl' (`pip3 install --upgrade`)

```
> youtube-dl.exe --version
2017.05.14
C:\Users\USERNAME\Desktop
> dzget -f mp3 --playlist http://www.deezer.com/playlist/2055454184
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 659, in _build_master
    ws.require(__requires__)
  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 967, in require
    needed = self.resolve(parse_requirements(requirements))
  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 858, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (youtube-dl 2017.5.14 (c:\python36\lib\site-packages), Requirement.parse('youtube-dl==2017.4.3'), {'Deezer-MP3-Downloader'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python36\Scripts\dzget-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 3017, in <module>
    @_call_aside
  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 3030, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 661, in _build_master
    return cls._build_from_requirements(__requires__)
  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 674, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 853, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'youtube-dl==2017.4.3' distribution was not found and is required by Deezer-MP3-Downloader
C
```

**Comment by artkpv** [comment]
Direct call to dzget.py after updating youtude-dl works

**Comment by creotiv** [comment]
thanks. will check asap

17 Май 2017 г. 19:41 пользователь "w1ld" <notifications@github.com> написал:

**Comment by creotiv** [comment]
Fixed.
