### ISSUE TITLE
Error in downloading playlist

### ISSUE THREAD

**Issue by nabilazri** [creotiv/deezer_playlist_mp3_downloader#9]
dzget -f mp3 -q 0 https://www.deezer.com/us/playlist/5128832884
b'## Fetching video urls...'
b'## Searching for Assala - ????? ????'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\Scripts\dzget-script.py", line 11, in <module>
    load_entry_point('Deezer-MP3-Downloader==0.0.7', 'console_scripts', 'dzget')()
  File "c:\users\User\appdata\local\programs\python\python37-32\lib\site-packages\deezermp3\dzget.py", line 152, in main
    dmp3.download_playlist(url)
  File "c:\users\nabil\appdata\local\programs\python\python37-32\lib\site-packages\deezermp3\dzget.py", line 90, in download_playlist
    ydl.download(list(self.urls_gen(data)))
  File "c:\users\User\appdata\local\programs\python\python37-32\lib\site-packages\deezermp3\dzget.py", line 48, in urls_gen
    video = self.regexp_video.finditer(res.content.decode('utf-8')).next().group(1)
AttributeError: 'callable_iterator' object has no attribute 'next'

**Comment by flenoir** [comment]
You should change .next() to

` .__next__()  `

at this line "video = self.regexp_video.finditer(res.content.decode('utf-8')).next().group(1)"

**Comment by nabilazri** [comment]
I did it, then I got this:
λ dzget https://www.deezer.com/us/album/6147987
b'## Fetching video urls...'
b'## Searching for Lights & Motion - Home'
Traceback (most recent call last):
  File "C:\Users\Nabil\AppData\Local\Programs\Python\Python37-32\Scripts\dzget-script.py", line 11, in <module>
    load_entry_point('Deezer-MP3-Downloader==0.0.7', 'console_scripts', 'dzget')()
  File "c:\users\nabil\appdata\local\programs\python\python37-32\lib\site-packages\deezermp3\dzget.py", line 152, in main
    dmp3.download_playlist(url)
  File "c:\users\nabil\appdata\local\programs\python\python37-32\lib\site-packages\deezermp3\dzget.py", line 90, in download_playlist
    ydl.download(list(self.urls_gen(data)))
  File "c:\users\nabil\appdata\local\programs\python\python37-32\lib\site-packages\deezermp3\dzget.py", line 48, in urls_gen
    video = self.regexp_video.finditer(res.content.decode('utf-8')).next().group(1)
AttributeError: 'callable_iterator' object has no attribute 'next'

**Comment by hakhagmon** [comment]
`>dzget album/6147987
b'## Fetching video urls...'
b'## Searching for Lights & Motion - Home'
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\Scripts\dzget-script.py", line 11, in <module>
    load_entry_point('Deezer-MP3-Downloader==0.0.7', 'console_scripts', 'dzget')()
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\site-packages\deezermp3\dzget.py", line 152, in main
    dmp3.download_playlist(url)
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\site-packages\deezermp3\dzget.py", line 90, in download_playlist
    ydl.download(list(self.urls_gen(data)))
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\site-packages\deezermp3\dzget.py", line 48, in urls_gen
    video = self.regexp_video.finditer(res.content.decode('utf-8')).next().group(1)
AttributeError: 'callable_iterator' object has no attribute 'next'`
